version: '3'
services:
    discord:
      container_name: suggestions-bot
      build:
        context: .
        dockerfile: ./Dockerfile
      restart: always
      environment:
      - NODE_ENV=production